name: 'Release: Create Pull Request'

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'The branch, tag, or commit to create this release PR from.'
        required: true
        default: 'master'

      release-type:
        description: 'A SemVer release type.'
        required: true
        type: choice
        default: 'minor'
        options:
          - patch
          - minor
          - major

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.base-branch }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x

      - run: npm install --prefix=.github/scripts --no-package-lock

      - name: Setup corepack and pnpm
        run: |
          npm i -g corepack@0.33
          corepack enable

      - name: Bump package versions
        run: |
          echo "NEXT_RELEASE=$(node .github/scripts/bump-versions.mjs)" >> "$GITHUB_ENV"
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      - name: Update Changelog
        env:
          NEXT_RELEASE: ${{ env.NEXT_RELEASE }}
        run: node .github/scripts/update-changelog.mjs

      - name: Push the base branch
        env:
          BASE_BRANCH: ${{ github.event.inputs.base-branch }}
        run: |
          git push -f origin "${{ env.BASE_BRANCH }}:refs/heads/release/${{ env.NEXT_RELEASE }}"

      - name: Create Pull Request
        run: |
          gh pr create \
            --base "release/${{ env.NEXT_RELEASE }}" \
            --head "release-pr/${{ env.NEXT_RELEASE }}" \
            --title ":rocket: Release ${{ env.NEXT_RELEASE }}" \
            --body "Automated release PR for version ${{ env.NEXT_RELEASE }}. This PR contains the changes for the ${{ env.NEXT_RELEASE }} release. Please review the changes and merge if appropriate." \
            --label "release,release:${{ github.event.inputs.release-type }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
